import {
  APISettings,
  IntegrationRecord,
  PlatformDefinition,
  StoreOption,
} from "./integrations-types";

export const PLATFORMS_CATALOG: PlatformDefinition[] = [
  // Stores
  {
    id: "shopify",
    name: "Shopify",
    category: "store",
    categoryLabel: "Stores",
    description: "Sync customers, products, and orders from Shopify.",
    availability: "available",
    isStoreWorkspace: true,
    logoType: "shopify",
    defaultName: "Northstar Shopify Store",
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    category: "store",
    categoryLabel: "Stores",
    description: "Connect your WooCommerce store and keep loyalty activity updated.",
    availability: "available",
    isStoreWorkspace: true,
    logoType: "woocommerce",
    defaultName: "Northstar WooCommerce Store",
  },

  // Point of sale
  {
    id: "shopify_pos",
    name: "Shopify POS",
    category: "pos",
    categoryLabel: "Point of sale",
    description: "Connect in-store sales to your Shopify customer activity.",
    availability: "available",
    isStoreWorkspace: true,
    logoType: "shopify_pos",
    defaultName: "Northstar Retail POS",
  },
  {
    id: "clover",
    name: "Clover",
    category: "pos",
    categoryLabel: "Point of sale",
    description: "Sync in-store customers and transactions.",
    availability: "available",
    isStoreWorkspace: true,
    logoType: "clover",
    defaultName: "Clover Terminal Station",
  },
  {
    id: "square",
    name: "Square",
    category: "pos",
    categoryLabel: "Point of sale",
    description: "Connect Square customers, orders, and payments.",
    availability: "available",
    isStoreWorkspace: true,
    logoType: "square",
    defaultName: "Square Register POS",
  },

  // Social
  {
    id: "instagram",
    name: "Instagram",
    category: "social",
    categoryLabel: "Social",
    description: "Connect your business profile to customer engagement.",
    availability: "available",
    isStoreWorkspace: false,
    logoType: "instagram",
    defaultName: "Northstar Instagram",
  },
  {
    id: "tiktok",
    name: "TikTok",
    category: "social",
    categoryLabel: "Social",
    description: "Connect your TikTok business account.",
    availability: "available",
    isStoreWorkspace: false,
    logoType: "tiktok",
    defaultName: "Northstar TikTok Business",
  },
  {
    id: "twitter",
    name: "Twitter / X",
    category: "social",
    categoryLabel: "Social",
    description: "Connect your business profile.",
    availability: "available",
    isStoreWorkspace: false,
    logoType: "twitter",
    defaultName: "Northstar Twitter / X",
  },

  // Reviews
  {
    id: "google_reviews",
    name: "Google Reviews",
    category: "reviews",
    categoryLabel: "Reviews",
    description: "Sync customer reviews from your Google Business Profile.",
    availability: "available",
    isStoreWorkspace: false,
    logoType: "google_reviews",
    defaultName: "Northstar Google Reviews",
  },
  {
    id: "trustpilot",
    name: "Trustpilot",
    category: "reviews",
    categoryLabel: "Reviews",
    description: "Connect Trustpilot review activity.",
    availability: "available",
    isStoreWorkspace: false,
    logoType: "trustpilot",
    defaultName: "Northstar Trustpilot",
  },

  // Developer
  {
    id: "custom_api",
    name: "Custom API",
    category: "custom_api",
    categoryLabel: "Developer",
    description: "Connect another platform using API endpoints and credentials.",
    availability: "available",
    isStoreWorkspace: false,
    logoType: "custom_api",
    defaultName: "Custom Warehouse Gateway",
  },
];

export const INITIAL_STORES: StoreOption[] = [
  {
    id: "northstar",
    name: "Northstar Goods",
    platform: "Shopify",
    avatarLetter: "N",
    status: "Connected",
    isWorkspace: true,
  },
  {
    id: "urban",
    name: "Urban Goods",
    platform: "WooCommerce",
    avatarLetter: "U",
    status: "Needs attention",
    isWorkspace: true,
  },
];

export const DEFAULT_API_SETTINGS: APISettings = {
  reloopinApiKey: "rw_live_9482••••••••••••••••••••3910Dpt",
  webhookSigningSecret: "whsec_8172••••••••••••••••••••9482f8a",
  syncInterval: "15m",
  ipWhitelist: ["192.168.1.100", "54.210.12.8"],
};

export const INITIAL_INTEGRATIONS: IntegrationRecord[] = [
  {
    id: "shopify-northstar",
    name: "Northstar Shopify Store",
    platform: "shopify",
    platformName: "Shopify",
    category: "store",
    status: "active",
    assignedStore: "Store workspace",
    assignedStoreIds: ["northstar"],
    isStoreWorkspace: true,
    workspaceStoreId: "northstar",
    storeUrl: "northstar-goods.myshopify.com",
    connectedAt: "Jun 1, 2026 at 12:00 AM",
    lastSynced: "2 minutes ago",
    lastSyncedAt: "Sep 26, 2026 at 2:38 PM",
    nextScheduledSync: "In 13 minutes",
    activitySummary: "24 customers synced",
    stats: {
      customersSynced: 2486,
      productsSynced: 684,
      ordersSynced: 8420,
    },
    dataAccess: {
      customers: "available",
      products: "available",
      orders: "available",
      reviews: "unavailable",
    },
    syncSummary: {
      recordsSynced: 11590,
      recordsSkipped: 12,
      recordsFailed: 0,
      syncProgressPercent: 100,
      syncProgressText: "11,590 of 11,590 records",
    },
    credentials: {
      clientKeyMasked: "shpat_••••••••••••••••4892",
      clientSecretMasked: "••••••••••••••••",
      apiKeyMasked: "rw_••••••••••••••Dpt",
      keyLastRotated: "Jun 1, 2026",
    },
    syncRecords: [
      {
        dataType: "Customers",
        synced: 2486,
        skipped: 4,
        failed: 0,
        lastSynced: "2 minutes ago",
        status: "Complete",
      },
      {
        dataType: "Products",
        synced: 684,
        skipped: 0,
        failed: 0,
        lastSynced: "2 minutes ago",
        status: "Complete",
      },
      {
        dataType: "Orders",
        synced: 8420,
        skipped: 8,
        failed: 0,
        lastSynced: "2 minutes ago",
        status: "Complete",
      },
      {
        dataType: "Reviews",
        synced: 0,
        skipped: 0,
        failed: 0,
        lastSynced: "Never synced",
        status: "Skipped",
      },
    ],
    syncErrors: [],
    activityLog: [
      {
        id: "act-1",
        event: "Sync completed",
        description: "Incremental sync updated 24 customers and 8 new orders.",
        result: "Success",
        performedBy: "System sync worker",
        date: "2 minutes ago",
      },
      {
        id: "act-2",
        event: "Connection tested",
        description: "Manual connection test verified customer and product read access.",
        result: "Success",
        performedBy: "Alex Morgan (Owner)",
        date: "Today at 10:14 AM",
      },
      {
        id: "act-3",
        event: "Integration connected",
        description: "Shopify OAuth app authorized and initial catalog sync completed.",
        result: "Success",
        performedBy: "Alex Morgan (Owner)",
        date: "Jun 1, 2026 at 12:00 AM",
      },
    ],
  },
  {
    id: "woocommerce-urban",
    name: "Urban Goods WooCommerce",
    platform: "woocommerce",
    platformName: "WooCommerce",
    category: "store",
    status: "needs_attention",
    statusIssue: "Customer and order data available, but product sync timed out.",
    assignedStore: "Store workspace",
    assignedStoreIds: ["urban"],
    isStoreWorkspace: true,
    workspaceStoreId: "urban",
    storeUrl: "https://urbangoods.example.com",
    connectedAt: "May 18, 2026 at 3:30 PM",
    lastSynced: "6 hours ago",
    lastSyncedAt: "Sep 26, 2026 at 8:30 AM",
    nextScheduledSync: "Sync retry pending",
    activitySummary: "Sync failed",
    stats: {
      customersSynced: 1240,
      productsSynced: 426,
      ordersSynced: 3180,
    },
    dataAccess: {
      customers: "available",
      products: "limited",
      orders: "available",
      reviews: "unavailable",
    },
    syncSummary: {
      recordsSynced: 4846,
      recordsSkipped: 18,
      recordsFailed: 3,
      syncProgressPercent: 94,
      syncProgressText: "4,846 of 4,867 records",
    },
    credentials: {
      clientKeyMasked: "ck_••••••••••••••••2918",
      clientSecretMasked: "••••••••••••••••",
      apiKeyMasked: "rw_••••••••••••••Dpt",
      keyLastRotated: "May 18, 2026",
    },
    syncRecords: [
      {
        dataType: "Customers",
        synced: 1240,
        skipped: 2,
        failed: 0,
        lastSynced: "6 hours ago",
        status: "Complete",
      },
      {
        dataType: "Products",
        synced: 426,
        skipped: 14,
        failed: 3,
        lastSynced: "6 hours ago",
        status: "Failed",
      },
      {
        dataType: "Orders",
        synced: 3180,
        skipped: 2,
        failed: 0,
        lastSynced: "6 hours ago",
        status: "Complete",
      },
      {
        dataType: "Reviews",
        synced: 0,
        skipped: 0,
        failed: 0,
        lastSynced: "Never synced",
        status: "Skipped",
      },
    ],
    syncErrors: [
      {
        id: "err-1",
        record: "Product SKU-UG-882 (Canvas Backpack)",
        dataType: "Product",
        issue: "Malformed price currency attribute 'EUR' expected 'USD'",
        lastAttempt: "6 hours ago",
        status: "pending",
      },
      {
        id: "err-2",
        record: "Product SKU-UG-910 (Wool Beanie)",
        dataType: "Product",
        issue: "Missing required catalog inventory schema identifier",
        lastAttempt: "6 hours ago",
        status: "pending",
      },
      {
        id: "err-3",
        record: "Product SKU-UG-441 (Ceramic Tumbler)",
        dataType: "Product",
        issue: "Gateway timeout (HTTP 504) while reading product variant options",
        lastAttempt: "6 hours ago",
        status: "pending",
      },
    ],
    activityLog: [
      {
        id: "act-u1",
        event: "Sync failed",
        description: "Incremental product catalog sync timed out on 3 variant records.",
        result: "Failed",
        performedBy: "System sync worker",
        date: "6 hours ago",
      },
      {
        id: "act-u2",
        event: "Credentials changed",
        description: "WooCommerce REST API consumer key updated by merchant.",
        result: "Info",
        performedBy: "Alex Morgan (Owner)",
        date: "Yesterday at 4:15 PM",
      },
      {
        id: "act-u3",
        event: "Integration connected",
        description: "WooCommerce store connection verified and webhooks active.",
        result: "Success",
        performedBy: "Alex Morgan (Owner)",
        date: "May 18, 2026 at 3:30 PM",
      },
    ],
  },
  {
    id: "google-reviews-northstar",
    name: "Northstar Google Reviews",
    platform: "google_reviews",
    platformName: "Google Reviews",
    category: "reviews",
    status: "active",
    assignedStore: "Northstar Goods",
    assignedStoreIds: ["northstar"],
    isStoreWorkspace: false,
    connectedAt: "Jul 10, 2026 at 11:20 AM",
    lastSynced: "18 minutes ago",
    lastSyncedAt: "Sep 26, 2026 at 2:22 PM",
    nextScheduledSync: "In 42 minutes",
    activitySummary: "12 reviews imported",
    socialHandle: "Northstar Goods (Portland Downtown)",
    stats: {
      customersSynced: 0,
      productsSynced: 0,
      ordersSynced: 0,
      reviewsSynced: 468,
    },
    dataAccess: {
      customers: "unavailable",
      products: "unavailable",
      orders: "unavailable",
      reviews: "available",
    },
    syncSummary: {
      recordsSynced: 468,
      recordsSkipped: 3,
      recordsFailed: 0,
      syncProgressPercent: 100,
      syncProgressText: "468 of 468 reviews",
    },
    credentials: {
      clientKeyMasked: "gsuite_••••••••••••••••1092",
      clientSecretMasked: "••••••••••••••••",
      apiKeyMasked: "rw_••••••••••••••Dpt",
      keyLastRotated: "Jul 10, 2026",
    },
    syncRecords: [
      {
        dataType: "Customers",
        synced: 0,
        skipped: 0,
        failed: 0,
        lastSynced: "Never synced",
        status: "Skipped",
      },
      {
        dataType: "Products",
        synced: 0,
        skipped: 0,
        failed: 0,
        lastSynced: "Never synced",
        status: "Skipped",
      },
      {
        dataType: "Orders",
        synced: 0,
        skipped: 0,
        failed: 0,
        lastSynced: "Never synced",
        status: "Skipped",
      },
      {
        dataType: "Reviews",
        synced: 468,
        skipped: 3,
        failed: 0,
        lastSynced: "18 minutes ago",
        status: "Complete",
      },
    ],
    syncErrors: [],
    activityLog: [
      {
        id: "act-g1",
        event: "Sync completed",
        description: "Imported 12 verified merchant customer reviews and star ratings.",
        result: "Success",
        performedBy: "System sync worker",
        date: "18 minutes ago",
      },
      {
        id: "act-g2",
        event: "Integration connected",
        description: "Google Business Profile OAuth authorized for Portland Downtown location.",
        result: "Success",
        performedBy: "Alex Morgan (Owner)",
        date: "Jul 10, 2026 at 11:20 AM",
      },
    ],
  },
  {
    id: "instagram-northstar",
    name: "Northstar Instagram",
    platform: "instagram",
    platformName: "Instagram",
    category: "social",
    status: "paused",
    assignedStore: "Northstar Goods",
    assignedStoreIds: ["northstar"],
    isStoreWorkspace: false,
    connectedAt: "Aug 4, 2026 at 9:00 AM",
    lastSynced: "Yesterday",
    lastSyncedAt: "Sep 25, 2026 at 5:00 PM",
    nextScheduledSync: "Paused by merchant",
    activitySummary: "No recent changes",
    socialHandle: "@northstargoods",
    stats: {
      customersSynced: 1120,
      productsSynced: 0,
      ordersSynced: 0,
      reviewsSynced: 0,
    },
    dataAccess: {
      customers: "available",
      products: "unavailable",
      orders: "unavailable",
      reviews: "unavailable",
    },
    syncSummary: {
      recordsSynced: 1120,
      recordsSkipped: 0,
      recordsFailed: 0,
      syncProgressPercent: 100,
      syncProgressText: "1,120 of 1,120 profiles",
    },
    credentials: {
      clientKeyMasked: "ig_meta_••••••••••••••••7710",
      clientSecretMasked: "••••••••••••••••",
      apiKeyMasked: "rw_••••••••••••••Dpt",
      keyLastRotated: "Aug 4, 2026",
    },
    syncRecords: [
      {
        dataType: "Customers",
        synced: 1120,
        skipped: 0,
        failed: 0,
        lastSynced: "Yesterday",
        status: "Complete",
      },
      {
        dataType: "Products",
        synced: 0,
        skipped: 0,
        failed: 0,
        lastSynced: "Never synced",
        status: "Skipped",
      },
      {
        dataType: "Orders",
        synced: 0,
        skipped: 0,
        failed: 0,
        lastSynced: "Never synced",
        status: "Skipped",
      },
      {
        dataType: "Reviews",
        synced: 0,
        skipped: 0,
        failed: 0,
        lastSynced: "Never synced",
        status: "Skipped",
      },
    ],
    syncErrors: [],
    activityLog: [
      {
        id: "act-i1",
        event: "Integration paused",
        description: "Merchant paused Instagram automated engagement syncing.",
        result: "Warning",
        performedBy: "Alex Morgan (Owner)",
        date: "Yesterday at 5:02 PM",
      },
      {
        id: "act-i2",
        event: "Integration connected",
        description: "Instagram Business Profile @northstargoods connected.",
        result: "Success",
        performedBy: "Alex Morgan (Owner)",
        date: "Aug 4, 2026 at 9:00 AM",
      },
    ],
  },
];
