import {
  Customer,
  SupportedFieldDefinition,
  ImportHistoryRecord,
} from "./customer-types";

export const PROTOTYPE_IMPORT_LIMITS = {
  maxSizeBytes: 10 * 1024 * 1024, // 10 MB
  maxSizeLabel: "10 MB",
  maxRows: 50000,
  maxRowsLabel: "50,000 rows",
};

export const SUPPORTED_FIELDS_METADATA: SupportedFieldDefinition[] = [
  {
    field: "First name",
    templateColumn: "first_name",
    required: true,
    format: "Text",
    example: "Maya",
  },
  {
    field: "Last name",
    templateColumn: "last_name",
    required: true,
    format: "Text",
    example: "Chen",
  },
  {
    field: "Email",
    templateColumn: "email",
    required: true,
    format: "Valid email",
    example: "maya@example.com",
  },
  {
    field: "Phone",
    templateColumn: "phone",
    required: false,
    format: "Text with country code",
    example: "+1 415 555 0142",
  },
  {
    field: "Date of birth",
    templateColumn: "date_of_birth",
    required: false,
    format: "YYYY-MM-DD",
    example: "1994-08-21",
  },
  {
    field: "Loyalty member",
    templateColumn: "loyalty_member",
    required: false,
    format: "TRUE or FALSE",
    example: "TRUE",
  },
  {
    field: "Current points",
    templateColumn: "points_balance",
    required: false,
    format: "Whole number, 0 or more",
    example: "1250",
  },
  {
    field: "Lifetime points",
    templateColumn: "lifetime_points",
    required: false,
    format: "Whole number, 0 or more",
    example: "3200",
  },
  {
    field: "Customer status",
    templateColumn: "status",
    required: false,
    format: "ACTIVE or INACTIVE",
    example: "ACTIVE",
  },
  {
    field: "External customer ID",
    templateColumn: "external_customer_id",
    required: false,
    format: "Text",
    example: "WC-10482",
  },
  {
    field: "Joined date",
    templateColumn: "joined_at",
    required: false,
    format: "YYYY-MM-DD",
    example: "2025-03-14",
  },
  {
    field: "City",
    templateColumn: "city",
    required: false,
    format: "Text",
    example: "San Francisco",
  },
  {
    field: "Region",
    templateColumn: "region",
    required: false,
    format: "Text",
    example: "California",
  },
  {
    field: "Country",
    templateColumn: "country",
    required: false,
    format: "Text",
    example: "United States",
  },
  {
    field: "Postal code",
    templateColumn: "postal_code",
    required: false,
    format: "Text",
    example: "94107",
  },
];

export const SAMPLE_TEMPLATE_CSV = `first_name,last_name,email,phone,date_of_birth,loyalty_member,points_balance,lifetime_points,status,external_customer_id,joined_at,city,region,country,postal_code
Maya,Chen,maya@example.com,+14155550142,1994-08-21,TRUE,1250,3200,ACTIVE,WC-10482,2025-03-14,San Francisco,California,United States,94107
Daniel,Kim,daniel@example.com,,1989-11-06,TRUE,0,0,ACTIVE,WC-10483,2026-01-10,Seattle,Washington,United States,98101`;

export const initialCustomers: Customer[] = [
  {
    id: "cust-01",
    name: "Ram Karki",
    firstName: "Ram",
    lastName: "Karki",
    email: "ramkarki@gmail.com",
    phone: "+1 (555) 234-8901",
    dateOfBirth: "1992-05-14",
    vipTier: "silver",
    pointBalance: 2450,
    lifetimeValue: 2840,
    lifetimePoints: 3700,
    pointsRedeemed: 1250,
    rewardsRedeemedCount: 4,
    status: "active",
    loyaltyMember: true,
    lastActivity: "3 hrs ago",
    joinedDate: "Mar 12, 2025",
    totalOrders: 18,
    externalCustomerId: "WC-8910",
    city: "San Francisco",
    region: "California",
    country: "United States",
    postalCode: "94107",
    notes: "VIP customer since 2025. Prefers weekend promotional emails.",
    transactions: [
      {
        id: "tx-101",
        date: "Today, 2:15 PM",
        type: "earned",
        points: 250,
        reason: "Points earned on order #1092",
        orderNumber: "#1092",
      },
      {
        id: "tx-102",
        date: "Sep 25, 2026",
        type: "redeemed",
        points: -500,
        reason: "Redeemed for $25 voucher reward",
        orderNumber: "#1088",
      },
      {
        id: "tx-103",
        date: "Sep 18, 2026",
        type: "adjusted",
        points: 150,
        reason: "Customer support courtesy",
        note: "Delivery delay compensation granted by admin.",
        performedBy: "Alex (Support)",
      },
      {
        id: "tx-104",
        date: "Sep 10, 2026",
        type: "bonus",
        points: 500,
        reason: "Birthday celebration bonus",
      },
      {
        id: "tx-105",
        date: "Aug 28, 2026",
        type: "earned",
        points: 380,
        reason: "Points earned on order #1045",
        orderNumber: "#1045",
      },
    ],
    orders: [
      {
        id: "ord-1092",
        orderNumber: "#1092",
        date: "Today, 2:15 PM",
        total: 185.0,
        itemsCount: 3,
        pointsEarned: 250,
        status: "completed",
      },
      {
        id: "ord-1088",
        orderNumber: "#1088",
        date: "Sep 25, 2026",
        total: 210.5,
        itemsCount: 4,
        pointsEarned: 210,
        status: "completed",
      },
      {
        id: "ord-1045",
        orderNumber: "#1045",
        date: "Aug 28, 2026",
        total: 380.0,
        itemsCount: 6,
        pointsEarned: 380,
        status: "completed",
      },
    ],
  },
  {
    id: "cust-02",
    name: "Ram Karki",
    firstName: "Ram",
    lastName: "Karki",
    email: "ramkarki.gold@gmail.com",
    phone: "+1 (555) 782-4120",
    dateOfBirth: "1988-11-20",
    vipTier: "gold",
    pointBalance: 2340,
    lifetimeValue: 2840,
    lifetimePoints: 4200,
    pointsRedeemed: 1860,
    rewardsRedeemedCount: 5,
    status: "active",
    loyaltyMember: true,
    lastActivity: "5 mins ago",
    joinedDate: "Jan 18, 2025",
    totalOrders: 15,
    externalCustomerId: "WC-9022",
    city: "Austin",
    region: "Texas",
    country: "United States",
    postalCode: "78701",
    notes: "High repeat order frequency. Gold tier member.",
    transactions: [
      {
        id: "tx-201",
        date: "Just now",
        type: "earned",
        points: 120,
        reason: "Points earned on order #1094",
        orderNumber: "#1094",
      },
      {
        id: "tx-202",
        date: "Sep 22, 2026",
        type: "bonus",
        points: 300,
        reason: "Tier achievement bonus: Gold Club",
      },
      {
        id: "tx-203",
        date: "Sep 15, 2026",
        type: "redeemed",
        points: -400,
        reason: "Redeemed for Free Shipping voucher",
        orderNumber: "#1072",
      },
    ],
    orders: [
      {
        id: "ord-1094",
        orderNumber: "#1094",
        date: "Today, 4:40 PM",
        total: 95.0,
        itemsCount: 2,
        pointsEarned: 120,
        status: "completed",
      },
      {
        id: "ord-1072",
        orderNumber: "#1072",
        date: "Sep 15, 2026",
        total: 140.0,
        itemsCount: 3,
        pointsEarned: 140,
        status: "completed",
      },
    ],
  },
  {
    id: "cust-03",
    name: "Ram Karki",
    firstName: "Ram",
    lastName: "Karki",
    email: "ramkarki.plat@gmail.com",
    phone: "+1 (555) 890-3311",
    dateOfBirth: "1990-03-12",
    vipTier: "platinum",
    pointBalance: 1840,
    lifetimeValue: 2840,
    lifetimePoints: 5900,
    pointsRedeemed: 4060,
    rewardsRedeemedCount: 8,
    status: "inactive",
    loyaltyMember: true,
    lastActivity: "1 year ago",
    joinedDate: "Nov 04, 2024",
    totalOrders: 22,
    externalCustomerId: "WC-7811",
    city: "New York",
    region: "New York",
    country: "United States",
    postalCode: "10001",
    notes: "Long time customer, inactive for 12 months. Eligible for winback campaign.",
    transactions: [
      {
        id: "tx-301",
        date: "Oct 14, 2025",
        type: "redeemed",
        points: -1000,
        reason: "Redeemed for $50 store credit",
        orderNumber: "#0841",
      },
      {
        id: "tx-302",
        date: "Sep 20, 2025",
        type: "earned",
        points: 450,
        reason: "Points earned on order #0841",
        orderNumber: "#0841",
      },
    ],
    orders: [
      {
        id: "ord-0841",
        orderNumber: "#0841",
        date: "Oct 14, 2025",
        total: 450.0,
        itemsCount: 5,
        pointsEarned: 450,
        status: "completed",
      },
    ],
  },
  {
    id: "cust-04",
    name: "Priya Anand",
    firstName: "Priya",
    lastName: "Anand",
    email: "priya.anand@northstar.example",
    phone: "+1 (555) 441-2994",
    vipTier: "gold",
    pointBalance: 3120,
    lifetimeValue: 3450,
    lifetimePoints: 4800,
    pointsRedeemed: 1680,
    rewardsRedeemedCount: 4,
    status: "active",
    loyaltyMember: true,
    lastActivity: "18 mins ago",
    joinedDate: "Feb 10, 2025",
    totalOrders: 16,
    notes: "Active brand ambassador. Shared 8 referral links.",
    transactions: [
      {
        id: "tx-401",
        date: "Today, 3:30 PM",
        type: "bonus",
        points: 250,
        reason: "Referral reward: Friend completed purchase",
      },
      {
        id: "tx-402",
        date: "Sep 24, 2026",
        type: "earned",
        points: 310,
        reason: "Points earned on order #1086",
        orderNumber: "#1086",
      },
    ],
    orders: [
      {
        id: "ord-1086",
        orderNumber: "#1086",
        date: "Sep 24, 2026",
        total: 245.0,
        itemsCount: 3,
        pointsEarned: 310,
        status: "completed",
      },
    ],
  },
  {
    id: "cust-05",
    name: "Sarah Jenkins",
    firstName: "Sarah",
    lastName: "Jenkins",
    email: "sarah.j@enterprise.example",
    phone: "+1 (555) 773-1992",
    vipTier: "platinum",
    pointBalance: 6850,
    lifetimeValue: 8420,
    lifetimePoints: 11200,
    pointsRedeemed: 4350,
    rewardsRedeemedCount: 12,
    status: "active",
    loyaltyMember: true,
    lastActivity: "42 mins ago",
    joinedDate: "Dec 01, 2024",
    totalOrders: 34,
    notes: "Top 1% spender across all stores. VIP concierge member.",
    transactions: [
      {
        id: "tx-501",
        date: "Yesterday",
        type: "earned",
        points: 750,
        reason: "Points earned on order #1090",
        orderNumber: "#1090",
      },
      {
        id: "tx-502",
        date: "Sep 19, 2026",
        type: "redeemed",
        points: -1500,
        reason: "Redeemed exclusive VIP Gift Set",
        orderNumber: "#1079",
      },
    ],
    orders: [
      {
        id: "ord-1090",
        orderNumber: "#1090",
        date: "Sep 28, 2026",
        total: 580.0,
        itemsCount: 8,
        pointsEarned: 750,
        status: "completed",
      },
    ],
  },
  {
    id: "cust-06",
    name: "David Chen",
    firstName: "David",
    lastName: "Chen",
    email: "david.chen@pacific.example",
    phone: "+1 (555) 302-8845",
    vipTier: "silver",
    pointBalance: 980,
    lifetimeValue: 1240,
    lifetimePoints: 1500,
    pointsRedeemed: 520,
    rewardsRedeemedCount: 2,
    status: "loyalty_paused",
    loyaltyMember: true,
    lastActivity: "2 days ago",
    joinedDate: "Jun 14, 2025",
    totalOrders: 7,
    notes: "Loyalty point accrual temporarily paused per customer request.",
    transactions: [
      {
        id: "tx-601",
        date: "Sep 27, 2026",
        type: "earned",
        points: 180,
        reason: "Points earned on order #1082",
        orderNumber: "#1082",
      },
    ],
    orders: [
      {
        id: "ord-1082",
        orderNumber: "#1082",
        date: "Sep 27, 2026",
        total: 120.0,
        itemsCount: 2,
        pointsEarned: 180,
        status: "completed",
      },
    ],
  },
  {
    id: "cust-07",
    name: "Elena Rostova",
    firstName: "Elena",
    lastName: "Rostova",
    email: "elena.rostova@design.example",
    phone: "+1 (555) 912-3344",
    vipTier: "platinum",
    pointBalance: 4920,
    lifetimeValue: 5310,
    lifetimePoints: 7800,
    pointsRedeemed: 2880,
    rewardsRedeemedCount: 7,
    status: "active",
    loyaltyMember: true,
    lastActivity: "4 days ago",
    joinedDate: "Jan 03, 2025",
    totalOrders: 25,
    notes: "High loyalty engagement and frequent review writer.",
    transactions: [
      {
        id: "tx-701",
        date: "Sep 25, 2026",
        type: "bonus",
        points: 100,
        reason: "Left a verified product photo review",
      },
      {
        id: "tx-702",
        date: "Sep 14, 2026",
        type: "earned",
        points: 410,
        reason: "Points earned on order #1068",
        orderNumber: "#1068",
      },
    ],
    orders: [
      {
        id: "ord-1068",
        orderNumber: "#1068",
        date: "Sep 14, 2026",
        total: 310.0,
        itemsCount: 4,
        pointsEarned: 410,
        status: "completed",
      },
    ],
  },
  {
    id: "cust-08",
    name: "Marcus Vance",
    firstName: "Marcus",
    lastName: "Vance",
    email: "m.vance@vancetech.example",
    phone: "+1 (555) 604-9812",
    vipTier: "none",
    pointBalance: 0,
    lifetimeValue: 620,
    lifetimePoints: 0,
    pointsRedeemed: 0,
    rewardsRedeemedCount: 0,
    status: "inactive",
    loyaltyMember: false,
    lastActivity: "8 months ago",
    joinedDate: "Aug 19, 2025",
    totalOrders: 3,
    notes: "Guest checkout, not yet enrolled in loyalty rewards.",
    transactions: [],
    orders: [
      {
        id: "ord-0914",
        orderNumber: "#0914",
        date: "Jan 12, 2026",
        total: 110.0,
        itemsCount: 1,
        pointsEarned: 0,
        status: "completed",
      },
    ],
  },
];

export const initialImportHistory: ImportHistoryRecord[] = [
  {
    id: "imp-hist-01",
    fileName: "summer_shopify_customers.csv",
    importedBy: "Alex (Owner)",
    startedAt: "Sep 15, 2026 · 11:24 AM",
    status: "completed",
    importedCount: 1210,
    updatedCount: 45,
    failedCount: 0,
    skippedCount: 12,
  },
  {
    id: "imp-hist-02",
    fileName: "q2_retail_loyalty_batch.xlsx",
    importedBy: "Sarah (Marketing)",
    startedAt: "Aug 02, 2026 · 3:45 PM",
    status: "completed_with_issues",
    importedCount: 840,
    updatedCount: 12,
    failedCount: 6,
    skippedCount: 8,
  },
];
