import {
  BillingPlan,
  Subscription,
  UsageMetric,
  PaymentMethod,
  Invoice,
  ComparisonFeature,
} from "./billing-types";

export const initialBillingPlans: BillingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    monthlyPrice: 0,
    description: "For stores starting their first loyalty program.",
    customerLimit: 500,
    storeLimit: 1,
    teamMemberLimit: 2,
    monthlyEmailLimit: 1000,
    monthlyApiLimit: null,
    features: [
      "Up to 500 customers",
      "1 connected store",
      "3 earning rules",
      "1 VIP tier",
      "1,000 monthly email sends",
      "Standard analytics",
      "Community support",
    ],
    apiAccess: false,
    recommended: false,
  },
  {
    id: "growth",
    name: "Growth",
    monthlyPrice: 49,
    description: "For growing stores that need more customer capacity and automation.",
    customerLimit: 2000,
    storeLimit: 3,
    teamMemberLimit: 5,
    monthlyEmailLimit: 10000,
    monthlyApiLimit: null,
    features: [
      "Up to 2,000 customers",
      "3 connected stores",
      "10 earning rules",
      "3 VIP tiers",
      "10,000 monthly email sends",
      "Automated reward campaigns",
      "Advanced analytics",
      "5 team members",
      "Priority email support",
    ],
    apiAccess: false,
    recommended: true,
  },
  {
    id: "pro",
    name: "Pro",
    monthlyPrice: 149,
    description: "For established programs that need advanced controls and API access.",
    customerLimit: null, // Unlimited
    storeLimit: null, // Unlimited
    teamMemberLimit: 15,
    monthlyEmailLimit: 50000,
    monthlyApiLimit: 50000,
    features: [
      "Unlimited customers",
      "Unlimited connected stores",
      "Unlimited earning rules",
      "Unlimited VIP tiers",
      "50,000 monthly email sends",
      "Full REST & GraphQL API access",
      "Real-time analytics & export",
      "15 team members",
      "Dedicated account manager",
    ],
    apiAccess: true,
    recommended: false,
  },
];

export const initialSubscription: Subscription = {
  planId: "growth",
  status: "active",
  billingInterval: "monthly",
  currentPeriodStart: "18 September 2026",
  currentPeriodEnd: "18 October 2026",
  cancelAtPeriodEnd: false,
  billingMode: "direct",
};

export const initialUsageMetrics: UsageMetric[] = [
  {
    id: "customers",
    name: "Customers",
    current: 1620,
    limit: 2000,
    unit: "customers",
    supportingMessage: "You can add 380 more customers on your current plan.",
  },
  {
    id: "stores",
    name: "Connected stores",
    current: 2,
    limit: 3,
    unit: "stores",
    supportingMessage: "Space for 1 more connected store.",
  },
  {
    id: "team",
    name: "Team members",
    current: 3,
    limit: 5,
    unit: "members",
    supportingMessage: "2 seat invitations remaining.",
  },
  {
    id: "emails",
    name: "Monthly email sends",
    current: 6450,
    limit: 10000,
    unit: "emails",
    supportingMessage: "3,550 sends remaining in this cycle.",
  },
  {
    id: "api",
    name: "API requests",
    current: 0,
    limit: null,
    unit: "requests",
    supportingMessage: "API access is available on Pro.",
  },
];

export const initialPaymentMethods: PaymentMethod[] = [
  {
    id: "pm_default",
    brand: "visa",
    last4: "4242",
    expiryMonth: 8,
    expiryYear: 2028,
    billingName: "Alex Lawrence",
    country: "United States",
    postalCode: "94103",
    isPrimary: true,
    status: "valid",
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: "inv_1042",
    number: "INV-1042",
    billingPeriod: "18 Sep 2026 – 18 Oct 2026",
    planId: "growth",
    planName: "Growth plan",
    amount: 49.0,
    subtotal: 49.0,
    discount: 0,
    tax: 0,
    status: "paid",
    date: "18 Sep 2026",
    paidAt: "18 Sep 2026",
    merchantName: "Northstar Goods",
    billingEmail: "alex@northstargoods.com",
    paymentMethodSummary: "Visa ending in 4242",
    items: [
      {
        description: "Growth Plan — Monthly subscription (18 Sep 2026 – 18 Oct 2026)",
        amount: 49.0,
      },
    ],
  },
  {
    id: "inv_1031",
    number: "INV-1031",
    billingPeriod: "18 Aug 2026 – 18 Sep 2026",
    planId: "growth",
    planName: "Growth plan",
    amount: 49.0,
    subtotal: 49.0,
    discount: 0,
    tax: 0,
    status: "paid",
    date: "18 Aug 2026",
    paidAt: "18 Aug 2026",
    merchantName: "Northstar Goods",
    billingEmail: "alex@northstargoods.com",
    paymentMethodSummary: "Visa ending in 4242",
    items: [
      {
        description: "Growth Plan — Monthly subscription (18 Aug 2026 – 18 Sep 2026)",
        amount: 49.0,
      },
    ],
  },
  {
    id: "inv_1019",
    number: "INV-1019",
    billingPeriod: "18 Jul 2026 – 18 Aug 2026",
    planId: "growth",
    planName: "Growth plan",
    amount: 49.0,
    subtotal: 49.0,
    discount: 0,
    tax: 0,
    status: "paid",
    date: "18 Jul 2026",
    paidAt: "18 Jul 2026",
    merchantName: "Northstar Goods",
    billingEmail: "alex@northstargoods.com",
    paymentMethodSummary: "Visa ending in 4242",
    items: [
      {
        description: "Growth Plan — Monthly subscription (18 Jul 2026 – 18 Aug 2026)",
        amount: 49.0,
      },
    ],
  },
  {
    id: "inv_1008",
    number: "INV-1008",
    billingPeriod: "18 Jun 2026 – 18 Jul 2026",
    planId: "growth",
    planName: "Growth plan",
    amount: 49.0,
    subtotal: 49.0,
    discount: 0,
    tax: 0,
    status: "paid",
    date: "18 Jun 2026",
    paidAt: "18 Jun 2026",
    merchantName: "Northstar Goods",
    billingEmail: "alex@northstargoods.com",
    paymentMethodSummary: "Visa ending in 4242",
    items: [
      {
        description: "Growth Plan — Monthly subscription (18 Jun 2026 – 18 Jul 2026)",
        amount: 49.0,
      },
    ],
  },
];

export const featureComparisonMatrix: ComparisonFeature[] = [
  {
    name: "Customer limit",
    tooltip: "Active members enrolled in your loyalty program.",
    starter: "500",
    growth: "2,000",
    pro: "Unlimited",
  },
  {
    name: "Connected stores",
    tooltip: "Multi-store synchronization and centralized points balance.",
    starter: "1 store",
    growth: "Up to 3",
    pro: "Unlimited",
  },
  {
    name: "Earning rules",
    tooltip: "Points for purchases, social actions, birthdays, and referrals.",
    starter: "3 rules",
    growth: "10 rules",
    pro: "Unlimited",
  },
  {
    name: "VIP tiers",
    tooltip: "Tiered perks and multiplier rewards based on points or spending.",
    starter: "1 tier",
    growth: "3 tiers",
    pro: "Unlimited",
  },
  {
    name: "Reward campaigns",
    tooltip: "Time-limited promotions, point boosters, and flash rewards.",
    starter: "Basic",
    growth: "Automated",
    pro: "Advanced",
  },
  {
    name: "Email automations",
    tooltip: "Transactional and promotional loyalty emails sent to customers.",
    starter: "1,000 / mo",
    growth: "10,000 / mo",
    pro: "50,000 / mo",
  },
  {
    name: "Analytics & reports",
    tooltip: "Performance tracking, member churn, and redemption rates.",
    starter: "Standard",
    growth: "Advanced",
    pro: "Real-time + CSV",
  },
  {
    name: "Team members",
    tooltip: "Admin and staff access seats for managing the store program.",
    starter: "2 seats",
    growth: "5 seats",
    pro: "15 seats",
  },
  {
    name: "API access",
    tooltip: "REST & GraphQL developer APIs for custom integrations.",
    starter: false,
    growth: false,
    pro: true,
  },
  {
    name: "Support level",
    tooltip: "Guaranteed SLA and dedicated contact channels.",
    starter: "Community & Docs",
    growth: "Priority email",
    pro: "Dedicated manager",
  },
];

export const cancellationReasons = [
  { id: "too_expensive", label: "Too expensive" },
  { id: "missing_features", label: "Missing features" },
  { id: "not_using_enough", label: "Not using it enough" },
  { id: "technical_issues", label: "Technical issues" },
  { id: "switching_tools", label: "Switching tools" },
  { id: "other", label: "Other" },
];
