'use client';

import React from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Calculator } from 'lucide-react';

interface CalculationInfoDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

export function CalculationInfoDialog({ isOpen, onClose }: CalculationInfoDialogProps) {
  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-lg bg-white border border-[#ebebeb] p-6 text-[#0a0a0a]">
        <DialogHeader className="pb-3 border-b border-[#ebebeb]">
          <div className="flex items-center gap-2.5">
            <div className="size-8 rounded-lg bg-[#5f3ed8]/10 text-[#5f3ed8] flex items-center justify-center">
              <Calculator className="size-4" />
            </div>
            <div>
              <DialogTitle className="text-base font-semibold text-[#0a0a0a]">
                How loyalty metrics are calculated
              </DialogTitle>
              <DialogDescription className="text-xs text-[#71717a]">
                Standard formulas and attribution rules used in Reloopin Analytics
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <div className="py-4 space-y-4 text-xs">
          <div className="p-3.5 bg-[#fafafa] border border-[#ebebeb] rounded-xl space-y-1.5">
            <div className="font-semibold text-[#0a0a0a] flex items-center justify-between">
              <span>Member revenue share</span>
              <span className="font-mono text-[#5f3ed8] font-bold">38%</span>
            </div>
            <p className="text-[#52525b] text-[11px] leading-relaxed">
              Gross merchandise volume generated by verified loyalty members divided by total store revenue across all channels in the period.
            </p>
          </div>

          <div className="p-3.5 bg-[#fafafa] border border-[#ebebeb] rounded-xl space-y-1.5">
            <div className="font-semibold text-[#0a0a0a] flex items-center justify-between">
              <span>Member repeat purchase rate</span>
              <span className="font-mono text-emerald-600 font-bold">87%</span>
            </div>
            <p className="text-[#52525b] text-[11px] leading-relaxed">
              The percentage of enrolled members with 2 or more lifetime orders. Non-member benchmark is calculated over the same store cohort.
            </p>
          </div>

          <div className="p-3.5 bg-[#fafafa] border border-[#ebebeb] rounded-xl space-y-1.5">
            <div className="font-semibold text-[#0a0a0a] flex items-center justify-between">
              <span>Program return (ROI)</span>
              <span className="font-mono text-[#5f3ed8] font-bold">$23.10 : $1</span>
            </div>
            <p className="text-[#52525b] text-[11px] leading-relaxed">
              Attributed loyalty member revenue ($519,430) divided by the total claimed discount value and reward redemption cost ($22,540).
            </p>
          </div>

          <div className="p-3.5 bg-amber-50/50 border border-amber-200/80 rounded-xl space-y-1.5">
            <div className="font-semibold text-amber-900 flex items-center justify-between">
              <span>Outstanding point liability</span>
              <span className="font-mono text-amber-700 font-bold">$32,400</span>
            </div>
            <p className="text-amber-800 text-[11px] leading-relaxed">
              Total unredeemed points held by active members (1.62M points) valued at the nominal redemption exchange rate of $0.02 per point.
            </p>
          </div>
        </div>

        <div className="pt-3 border-t border-[#ebebeb] flex justify-end">
          <Button
            type="button"
            onClick={onClose}
            className="h-8 px-4 text-xs font-semibold bg-[#5f3ed8] hover:bg-[#5034b8] text-white"
          >
            Got it
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

