import {
  UserProfile,
  StoreProfile,
  BrandingSettings,
  TeamMember,
  RoleCapability,
  NotificationGroup,
  SummaryPreferences,
  StoreOption,
} from "./settings-types";

export const initialCurrentUser: UserProfile = {
  id: "user-olivia-morgan",
  firstName: "Olivia",
  lastName: "Morgan",
  email: "olivia@northstargoods.com",
  pendingEmail: undefined,
  emailVerificationStatus: "none",
  language: "en",
  timezone: "America/New_York",
  passwordLastChanged: "3 months ago",
};

export const availableStores: StoreOption[] = [
  {
    id: "northstar",
    name: "Northstar Goods",
    platform: "Shopify",
    isConnected: true,
  },
  {
    id: "urban",
    name: "Urban Goods",
    platform: "WooCommerce",
    isConnected: true,
  },
];

export const initialStoreProfiles: Record<string, StoreProfile> = {
  northstar: {
    id: "northstar",
    name: "Northstar Goods",
    publicDisplayName: "Northstar Rewards",
    website: "https://northstargoods.com",
    supportEmail: "support@northstargoods.com",
    supportPhoneCountryCode: "+1",
    supportPhoneNumber: "555-234-5678",
    address: {
      addressLine: "120 Franklin St, Suite 400",
      city: "New York",
      region: "NY",
      country: "United States",
      postalCode: "10013",
    },
    currency: "USD",
    currencySyncedFrom: "Shopify",
    currencyLastSynced: "5 minutes ago",
    timezone: "America/New_York",
    isDisconnected: false,
  },
  urban: {
    id: "urban",
    name: "Urban Goods",
    publicDisplayName: "Urban Perks",
    website: "https://urbangoods.co",
    supportEmail: "hello@urbangoods.co",
    supportPhoneCountryCode: "+1",
    supportPhoneNumber: "555-891-2345",
    address: {
      addressLine: "450 Mission St, 2nd Floor",
      city: "San Francisco",
      region: "CA",
      country: "United States",
      postalCode: "94105",
    },
    currency: "USD",
    currencySyncedFrom: "WooCommerce",
    currencyLastSynced: "12 minutes ago",
    timezone: "America/Los_Angeles",
    isDisconnected: false,
  },
};

export const initialBrandings: Record<string, BrandingSettings> = {
  northstar: {
    storeId: "northstar",
    logoUrl: undefined,
    brandColor: "#7B72EB",
    senderName: "Northstar Goods",
  },
  urban: {
    storeId: "urban",
    logoUrl: undefined,
    brandColor: "#2563EB",
    senderName: "Urban Goods",
  },
};

export const initialTeamMembers: TeamMember[] = [
  {
    id: "mem-olivia-morgan",
    name: "Olivia Morgan",
    email: "olivia@northstargoods.com",
    role: "owner",
    status: "active",
    storeAccess: "all",
    lastActive: "Active now",
    isCurrentUser: true,
  },
  {
    id: "mem-ava-carter",
    name: "Ava Carter",
    email: "ava@northstargoods.com",
    role: "admin",
    status: "active",
    storeAccess: ["northstar", "urban"],
    lastActive: "2 hours ago",
    isCurrentUser: false,
  },
  {
    id: "mem-daniel-kim",
    name: "Daniel Kim",
    email: "daniel@northstargoods.com",
    role: "staff",
    status: "active",
    storeAccess: ["northstar"],
    lastActive: "Yesterday",
    isCurrentUser: false,
  },
  {
    id: "mem-maya-patel",
    name: "Maya Patel",
    email: "maya@northstargoods.com",
    role: "viewer",
    status: "invitation_pending",
    storeAccess: ["northstar"],
    lastActive: "Never signed in",
    isCurrentUser: false,
    invitationSentDate: "Sep 24, 2026",
    invitationToken: "tok_maya_viewer_2026",
  },
];

export const sampleAdditionalMembers: TeamMember[] = [
  {
    id: "mem-liam-chen",
    name: "Liam Chen",
    email: "liam@northstargoods.com",
    role: "staff",
    status: "active",
    storeAccess: ["northstar", "urban"],
    lastActive: "3 days ago",
  },
  {
    id: "mem-sophia-rodriguez",
    name: "Sophia Rodriguez",
    email: "sophia@northstargoods.com",
    role: "viewer",
    status: "active",
    storeAccess: ["urban"],
    lastActive: "1 week ago",
  },
];

export const roleCapabilityMatrix: RoleCapability[] = [
  {
    id: "view_dashboard",
    label: "View dashboard",
    owner: "allowed",
    admin: "allowed",
    staff: "allowed",
    viewer: "allowed",
  },
  {
    id: "view_analytics",
    label: "View analytics",
    owner: "allowed",
    admin: "allowed",
    staff: "allowed",
    viewer: "allowed",
  },
  {
    id: "manage_customers",
    label: "Manage customers",
    owner: "allowed",
    admin: "allowed",
    staff: "allowed",
    viewer: "read_only",
  },
  {
    id: "adjust_points",
    label: "Adjust customer points",
    owner: "allowed",
    admin: "allowed",
    staff: "allowed",
    viewer: "not_allowed",
  },
  {
    id: "manage_earning_rules",
    label: "Manage earning rules",
    owner: "allowed",
    admin: "allowed",
    staff: "not_allowed",
    viewer: "read_only",
  },
  {
    id: "manage_vip_tiers",
    label: "Manage VIP tiers",
    owner: "allowed",
    admin: "allowed",
    staff: "not_allowed",
    viewer: "read_only",
  },
  {
    id: "manage_rewards",
    label: "Manage rewards",
    owner: "allowed",
    admin: "allowed",
    staff: "allowed",
    viewer: "read_only",
  },
  {
    id: "manage_email_marketing",
    label: "Manage email marketing",
    owner: "allowed",
    admin: "allowed",
    staff: "not_allowed",
    viewer: "read_only",
  },
  {
    id: "manage_integrations",
    label: "Manage integrations",
    owner: "allowed",
    admin: "allowed",
    staff: "not_allowed",
    viewer: "not_allowed",
  },
  {
    id: "manage_store_settings",
    label: "Manage store settings",
    owner: "allowed",
    admin: "allowed",
    staff: "not_allowed",
    viewer: "read_only",
  },
  {
    id: "invite_members",
    label: "Invite team members",
    owner: "allowed",
    admin: "allowed", // Staff and Viewers only
    staff: "not_allowed",
    viewer: "not_allowed",
  },
  {
    id: "change_roles",
    label: "Change roles",
    owner: "allowed",
    admin: "not_allowed",
    staff: "not_allowed",
    viewer: "not_allowed",
  },
  {
    id: "manage_billing",
    label: "Manage billing",
    owner: "allowed",
    admin: "not_allowed",
    staff: "not_allowed",
    viewer: "not_allowed",
  },
  {
    id: "manage_api_keys",
    label: "Manage API keys",
    owner: "allowed",
    admin: "not_allowed",
    staff: "not_allowed",
    viewer: "not_allowed",
  },
  {
    id: "transfer_ownership",
    label: "Transfer ownership",
    owner: "allowed",
    admin: "not_allowed",
    staff: "not_allowed",
    viewer: "not_allowed",
  },
];

export const initialNotificationGroups: NotificationGroup[] = [
  {
    id: "store_integrations",
    title: "Store and integrations",
    description: "System health and synchronization alerts.",
    items: [
      {
        id: "store_disconnected",
        label: "Store disconnected",
        description: "Alert when a commerce store connection drops.",
        email: true,
        inApp: true,
        isCritical: true,
        lockedReason: "Store disconnection alerts must remain active for account security.",
      },
      {
        id: "store_reconnected",
        label: "Store reconnected",
        description: "Confirmation when a disconnected store comes back online.",
        email: true,
        inApp: true,
      },
      {
        id: "data_sync_failed",
        label: "Data sync failed",
        description: "Notice when order or customer syncing encounters errors.",
        email: true,
        inApp: true,
      },
      {
        id: "data_sync_completed",
        label: "Data sync completed",
        description: "Notice when large batch syncs finish successfully.",
        email: false,
        inApp: true,
      },
      {
        id: "integration_permission_expired",
        label: "Integration permission expired",
        description: "Notification when OAuth token renewal is required.",
        email: true,
        inApp: true,
      },
    ],
  },
  {
    id: "loyalty_program",
    title: "Loyalty program",
    description: "Operational triggers, campaigns, and point thresholds.",
    items: [
      {
        id: "earning_rule_paused",
        label: "Earning rule paused",
        description: "Notice when an earning rule is manually or automatically paused.",
        email: true,
        inApp: true,
      },
      {
        id: "reward_limit_reached",
        label: "Reward limit reached",
        description: "Alert when a reward coupon cap or redemption budget is hit.",
        email: true,
        inApp: true,
      },
      {
        id: "reward_campaign_expired",
        label: "Reward campaign expired",
        description: "Notice when a scheduled reward promotion reaches its end date.",
        email: false,
        inApp: true,
      },
      {
        id: "unusual_points_activity",
        label: "Unusual points activity",
        description: "Fraud protection alert for anomalous point issuance or redemptions.",
        email: true,
        inApp: true,
      },
      {
        id: "points_adjustment_completed",
        label: "Points adjustment completed",
        description: "Confirmation when a staff member manually adjusts customer balance.",
        email: false,
        inApp: true,
      },
    ],
  },
  {
    id: "customers_tiers",
    title: "Customers and tiers",
    description: "Significant milestone events and membership progressions.",
    items: [
      {
        id: "customer_vip_tier",
        label: "Customer reached a new VIP tier",
        description: "Celebration update when members cross into top tiers.",
        email: false,
        inApp: true,
      },
      {
        id: "customer_import_completed",
        label: "Customer import completed",
        description: "Summary report when CSV customer migrations finish.",
        email: true,
        inApp: true,
      },
      {
        id: "customer_import_failed",
        label: "Customer import failed",
        description: "Error alert if invalid customer rows block an import.",
        email: true,
        inApp: true,
      },
    ],
  },
  {
    id: "email_marketing",
    title: "Email marketing",
    description: "Campaign dispatch and automated flow delivery updates.",
    items: [
      {
        id: "campaign_scheduled",
        label: "Campaign scheduled",
        description: "Reminder before an email blast is queued for dispatch.",
        email: false,
        inApp: true,
      },
      {
        id: "campaign_sent",
        label: "Campaign sent",
        description: "Delivery summary once an email broadcast finishes.",
        email: true,
        inApp: true,
      },
      {
        id: "campaign_failed",
        label: "Campaign failed",
        description: "Critical alert if an email broadcast encounters delivery failure.",
        email: true,
        inApp: true,
      },
      {
        id: "automation_failed",
        label: "Automation failed",
        description: "Alert when a triggered lifecycle journey cannot run.",
        email: true,
        inApp: true,
      },
      {
        id: "sender_verification_required",
        label: "Sender verification required",
        description: "Alert when domain DNS or DKIM changes require re-verification.",
        email: true,
        inApp: true,
      },
    ],
  },
  {
    id: "team_account",
    title: "Team and account",
    description: "Security notifications and team membership changes.",
    items: [
      {
        id: "team_invitation_accepted",
        label: "Team invitation accepted",
        description: "Notice when an invited colleague creates their login.",
        email: true,
        inApp: true,
      },
      {
        id: "team_invitation_expired",
        label: "Team invitation expired",
        description: "Notice when a 7-day invitation link passes without acceptance.",
        email: false,
        inApp: true,
      },
      {
        id: "member_role_changed",
        label: "Member role changed",
        description: "Audit alert when access privileges or store scopes are edited.",
        email: true,
        inApp: true,
      },
      {
        id: "new_sign_in_detected",
        label: "New sign-in detected",
        description: "Security alert for logins from new devices, browsers, or locations.",
        email: true,
        inApp: true,
        isCritical: true,
        lockedReason: "Required account security alert.",
      },
      {
        id: "password_changed",
        label: "Password changed",
        description: "Immediate security notice whenever your password updates.",
        email: true,
        inApp: true,
        isCritical: true,
        lockedReason: "Required account security alert.",
      },
    ],
  },
  {
    id: "billing_usage",
    title: "Billing and usage",
    description: "Subscription status, plan quotas, and invoice receipts.",
    linkToBilling: true,
    items: [
      {
        id: "payment_failed",
        label: "Payment failed",
        description: "Urgent alert if subscription auto-renewal invoice cannot be processed.",
        email: true,
        inApp: true,
        isCritical: true,
        lockedReason: "Payment failure notices cannot be disabled for the account owner.",
      },
      {
        id: "invoice_available",
        label: "Invoice available",
        description: "Monthly tax receipts ready for download.",
        email: true,
        inApp: false,
      },
      {
        id: "customer_limit_approaching",
        label: "Customer limit approaching",
        description: "Warning when active members exceed 85% of tier quota.",
        email: true,
        inApp: true,
      },
      {
        id: "team_seat_limit_approaching",
        label: "Team seat limit approaching",
        description: "Warning when team invitations approach plan maximum.",
        email: false,
        inApp: true,
      },
    ],
  },
];

export const initialSummaryPreferences: SummaryPreferences = {
  weeklySummaryEnabled: true,
  weeklyDeliveryDay: "monday",
  monthlySummaryEnabled: true,
};

export const defaultTeamSeatLimit = 5;
